---
version: '3'
services:
  charra-dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: fraunhofer-sit/charra-dev-env:1.5.1
    restart: unless-stopped
    container_name: charra-dev-env
    volumes:
      - ".:/home/bob/charra"
    #ports:
    #  - "127.0.0.1:8080:8080"
    #command: >
    #  /bin/bash
  charra-attester:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: fraunhofer-sit/charra:1.5.1
    restart: unless-stopped
    container_name: charra-attester
    ports:
      - "127.0.0.1:5683:5683"
    command: >
      /home/bob/charra/bin/attester
  charra-verifier:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: fraunhofer-sit/charra:1.5.1
    restart: unless-stopped
    container_name: charra-verifier
    #ports:
    #  - "127.0.0.1:5683:5683"
    command: >
      /home/bob/charra/bin/verifier

